version: '3'
services:
  jupyter: # Jupyter Notebook
    build: ./pyspark-cassandra
    volumes:
      - ./jupyter:/home/jovyan
    ports:
      - "8888:8888" # Exposes port to be available externally
    environment:
      PYSPARK_SUBMIT_ARGS: '--packages com.datastax.spark:spark-cassandra-connector_2.11:2.5.1 pyspark-shell'
    # see https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html?highlight=start-notebook.sh#jupyter-server-options
    # 'mlrules' (better to stick to sha1 to avoid escaping those pesky literal dollar signs, see https://stackoverflow.com/questions/40619582/how-can-i-escape-a-dollar-sign-in-a-docker-compose-file)
    command: start-notebook.sh --NotebookApp.password='sha1:7b14dcc0fcd0:a01b354f5bb59e283527727811642bcc3dfb4b6c'
    # command: start-notebook.sh --NotebookApp.password='sha1:a536879cf56d:a895a85b375e09f7d6a8211cdcd0e87f16aa4e60'
